spring:
  application:
    name: manage_service

  datasource:
    url: "jdbc:mysql://localhost:3314/manage_service"
    username: root
    password: root

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

server:
  port: 8092
  servlet:
    context-path: /api/v1/manage-service
