spring:
  application:
    name: medical_prescription_service
  data:
    redis:
      host: localhost
      port: 6380


  datasource:
    url: "jdbc:mysql://localhost:3312/medical_prescription_service"
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8086
  servlet:
    context-path: /api/v1/medical-prescription-service

