services:
  mysql:
    image: "mysql:latest"
    container_name: "mysql_medical_prescription_service"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medical_prescription_service
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    ports:
      - "3312:3306"

  redis:
    image: redis:latest
    container_name: cache-redis
    ports:
      - "6380:6379"