services:
  Elasticsearch:
    image: elasticsearch:7.17.24
    container_name: elasticsearch
    restart: always
    volumes:
      - ./elastic/elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
      - '9200:9200'
    networks:
      - elk

  Kibana:
    image: kibana:7.17.24
    container_name: kibana
    restart: always
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - Elasticsearch
    networks:
      - elk
volumes:
  elastic_data: { }

networks:
  elk: