spring:
  application:
    name: bill_service

  datasource:
    url: "jdbc:mysql://localhost:3012/bill_service"
    password: root
    username: root

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

#  activemq:
#    broker-url: tcp://localhost:61616
#    user: admin
#    password: admin

#  flyway:
#    enabled: true
#    url: jdbc:mysql://localhost:3308/appointment_service
#    user: root
#    password: root
#    locations: classpath:db/migrations

server:
  servlet:
    context-path: /api/v1/bill-service
  port: 8090


#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui.html
