services:
  mysql:
    image: "mysql:latest"
    container_name: "mysql_warehouse_manager"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petcare
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    ports:
      - "2504:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
