
spring:
#  datasource:
#    url: jdbc:mysql://localhost:2501/petcare
#    username: root
#    password: root

  datasource:
    url: jdbc:mysql://localhost:2501/pet_care_manager
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      port: 6379
      host: localhost

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
flyway:
  locations: classpath:/db/migration
  baseline-on-migrate: true

server:
  port: 8090
  servlet:
    context-path: /api/v1