package com.pet_care.bill_service.entity;

import com.pet_care.bill_service.enums.VeterinaryCareStatus;
import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.FieldDefaults;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.util.Date;

// Lombok annotations to generate getters, setters, builders, and constructors
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
@FieldDefaults(level = AccessLevel.PRIVATE)
public class VeterinaryCare {

    // Primary key for the `veterinary_care` table
    @Id
    String name; // Name of the veterinary care service

    // Detailed description of the veterinary care service
    String description;

    // Enum representing the status of the veterinary care (e.g., ACTIVE, INACTIVE)
    @Enumerated(EnumType.STRING) // Maps the enum to a string in the database
    @Builder.Default // Sets a default value for this field during object construction
    VeterinaryCareStatus status = VeterinaryCareStatus.ACTIVE;

    // Price of the veterinary care service
    Double price;

    // Timestamp indicating when the record was created
    @CreationTimestamp // Automatically generated by Hibernate
    @Temporal(TemporalType.TIMESTAMP) // Stores both date and time
    Date createdAt;

    // Timestamp indicating the last time the record was updated
    @UpdateTimestamp // Automatically updated by Hibernate
    @Temporal(TemporalType.TIMESTAMP) // Stores both date and time
    Date updatedAt;
}
