spring:
  application:
    name: api_gateway

  cloud:
    gateway:
      mvc:
        routes:
          # Manage Service route
          - id: manage_service
            uri: http://localhost:8092
            predicates:
              - Path=/api/v1/manage-service/**

          # Identity Service route
          - id: identity_service
            uri: http://localhost:8091
            predicates:
              - Path=/api/v1/identity-service/**

          # Appointment Service route
          - id: appointment_service
            uri: http://localhost:8082
            predicates:
              - Path=/api/v1/appointment-service/**

          # Customer Service route
          - id: customer_service
            uri: http://localhost:8083
            predicates:
              - Path=/api/v1/customer-service/**

          # Employee Service route
          - id: employee_service
            uri: http://localhost:8084
            predicates:
              - Path=/api/v1/employee-service/**

          # Medicine Service route
          - id: medicine_service
            uri: http://localhost:8085
            predicates:
              - Path=/api/v1/medicine-service/**

          # Medical Prescription Service route
          - id: medical_prescription_service
            uri: http://localhost:8086
            predicates:
              - Path=/api/v1/medical-prescription-service/**

          # Payment Service route
          - id: payment_service
            uri: http://localhost:8089
            predicates:
              - Path=/api/v1/payment-service/**

          # Bill Service route
          - id: bill_service
            uri: http://localhost:8088
            predicates:
              - Path=/api/v1/bill-service/**

server:
  port: 8888 # Cổng của API Gateway

# Logging để ghi log các yêu cầu và phản hồi, hữu ích cho việc debug
logging:
  level:
    org.springframework.cloud.gateway: DEBUG



