spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]': # Matches all paths
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: appointment-service
          uri: lb://APPOINTMENT-SERVICE
          predicates:
            - Path=/api/v1/appointment-service/**

        - id: medical-prescription-service
          uri: lb://MEDICAL-PRESCRIPTION-SERVICE
          predicates:
            - Path=/api/v1/medical-prescription-service/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/