spring:
  application:
    name: employee_service

  datasource:
    url: "jdbc:mysql://localhost:3310/employee_service"
    username: root
    password: root

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

server:
  port: 8085
  servlet:
    context-path: /api/v1

random-avatar-url: https://api.multiavatar.com/
