services:
  mysql:
    image: "mysql"
    container_name: "mysql_bill_service"
    environment:
      MYSQL_DATABASE: bill_service
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3313:3306"