spring:
  application:
    name: notification_service



brevo:
  enabled: true
  key: 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
  url: https://api.brevo.com/v3/smtp/email

server:
  servlet:
    context-path: /api/v1
  port: 8087
