spring:
  application:
    name: medicine_service

  datasource:
    url: "jdbc:mysql://localhost:3311/medicine_service"
    username: root
    password: root

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

server:
  port: 8087
  servlet:
    context-path: /api/v1