spring:
  application:
    name: medicine_service

  datasource:
    url: "jdbc:mysql://localhost:3311/medicine_service"
    username: root
    password: root

  flyway:
    enabled: false
    url: jdbc:mysql://localhost:3311/medicine_service
    user: root
    password: root
    locations: classpath:db/migrations

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

server:
  port: 8080
  servlet:
    context-path: /api/v1/medicine-service

cloudinary:
  cloud-name: dxowhxfwj
  api-key: 493466681247413
  api-secret: QXjt9-bbjJK_TDjpZsoLJsAQ2Rk
