spring:
  application:
   name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HuyTinh/pet-care-config-source

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

server:
  port: 8246