insert into Caculation_units (name, status) values ('Tablet', 1);
insert into Caculation_units (name, status) values ('Box', 1);
insert into Caculation_units (name, status) values ('Bottle', 1);
insert into Caculation_units (name, status) values ('Blister Park', 1);
insert into Caculation_units (name, status) values ('Sachet', 1);
insert into Caculation_units (name, status) values ('Jar', 1);
insert into Caculation_units (name, status) values ('Bag', 1);
insert into Caculation_units (name, status) values ('Carton', 1);

insert into Locations (area, row_location, column_location, status) values ('A',1,1, 1);
insert into Locations (area, row_location, column_location, status) values ('A',2,1, 1);
insert into Locations (area, row_location, column_location, status) values ('A',3,1, 1);
insert into Locations (area, row_location, column_location, status) values ('A',4,1, 1);
insert into Locations (area, row_location, column_location, status) values ('A',5,1, 1);
insert into Locations (area, row_location, column_location, status) values ('A',1,2, 1);
insert into Locations (area, row_location, column_location, status) values ('A',2,2, 1);
insert into Locations (area, row_location, column_location, status) values ('A',3,2, 1);
insert into Locations (area, row_location, column_location, status) values ('A',4,2, 1);
insert into Locations (area, row_location, column_location, status) values ('A',5,2, 1);
insert into Locations (area, row_location, column_location, status) values ('A',1,3, 1);
insert into Locations (area, row_location, column_location, status) values ('A',2,3, 1);
insert into Locations (area, row_location, column_location, status) values ('A',3,3, 1);
insert into Locations (area, row_location, column_location, status) values ('A',4,3, 1);
insert into Locations (area, row_location, column_location, status) values ('A',5,3, 1);
insert into Locations (area, row_location, column_location, status) values ('A',1,4, 1);
insert into Locations (area, row_location, column_location, status) values ('A',2,4, 1);
insert into Locations (area, row_location, column_location, status) values ('A',3,4, 1);
insert into Locations (area, row_location, column_location, status) values ('A',4,4, 1);
insert into Locations (area, row_location, column_location, status) values ('A',5,4, 1);
insert into Locations (area, row_location, column_location, status) values ('A',1,5, 1);
insert into Locations (area, row_location, column_location, status) values ('A',2,5, 1);
insert into Locations (area, row_location, column_location, status) values ('A',3,5, 1);
insert into Locations (area, row_location, column_location, status) values ('A',4,5, 1);
insert into Locations (area, row_location, column_location, status) values ('A',5,5, 1);
insert into Locations (area, row_location, column_location, status) values ('B',1,1, 1);
insert into Locations (area, row_location, column_location, status) values ('B',2,1, 1);
insert into Locations (area, row_location, column_location, status) values ('B',3,1, 1);
insert into Locations (area, row_location, column_location, status) values ('B',4,1, 1);
insert into Locations (area, row_location, column_location, status) values ('B',5,1, 1);
insert into Locations (area, row_location, column_location, status) values ('B',1,2, 1);
insert into Locations (area, row_location, column_location, status) values ('B',2,2, 1);
insert into Locations (area, row_location, column_location, status) values ('B',3,2, 1);
insert into Locations (area, row_location, column_location, status) values ('B',4,2, 1);
insert into Locations (area, row_location, column_location, status) values ('B',5,2, 1);
insert into Locations (area, row_location, column_location, status) values ('B',1,3, 1);
insert into Locations (area, row_location, column_location, status) values ('B',2,3, 1);
insert into Locations (area, row_location, column_location, status) values ('B',3,3, 1);
insert into Locations (area, row_location, column_location, status) values ('B',4,3, 1);
insert into Locations (area, row_location, column_location, status) values ('B',5,3, 1);
insert into Locations (area, row_location, column_location, status) values ('B',1,4, 1);
insert into Locations (area, row_location, column_location, status) values ('B',2,4, 1);
insert into Locations (area, row_location, column_location, status) values ('B',3,4, 1);
insert into Locations (area, row_location, column_location, status) values ('B',4,4, 1);
insert into Locations (area, row_location, column_location, status) values ('B',5,4, 1);
insert into Locations (area, row_location, column_location, status) values ('B',1,5, 1);
insert into Locations (area, row_location, column_location, status) values ('B',2,5, 1);
insert into Locations (area, row_location, column_location, status) values ('B',3,5, 1);
insert into Locations (area, row_location, column_location, status) values ('B',4,5, 1);
insert into Locations (area, row_location, column_location, status) values ('B',5,5, 1);

insert into Manufacturers (name, status) values ('Zoetis', 1);
insert into Manufacturers (name, status) values ('Merck Animal Health', 1);
insert into Manufacturers (name, status) values ('Boehringer Ingelheim', 1);
insert into Manufacturers (name, status) values ('Elanco Animal Health', 1);
insert into Manufacturers (name, status) values ('Bayer Animal Health', 1);
insert into Manufacturers (name, status) values ('Virbac', 1);
insert into Manufacturers (name, status) values ('Dechra Pharmaceuticals', 1);
insert into Manufacturers (name, status) values ('Vetoquinol', 1);
insert into Manufacturers (name, status) values ('Ceva Santé Animale', 1);
insert into Manufacturers (name, status) values ('Phibro Animal Health', 1);
insert into Manufacturers (name, status) values ('Norbrook', 1);
insert into Manufacturers (name, status) values ('MSD', 1);
insert into Manufacturers (name, status) values ('Hester Biosciences', 1);
insert into Manufacturers (name, status) values ('Covetrus', 1);
insert into Manufacturers (name, status) values ('IDEXX Laboratories Inc', 1);